name: Publish to WordPress.org

on:
  release:
    types: [published]

jobs:
  publish:
    name: Publish release to WordPress.org
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: WordPress Plugin Deploy
        if: "! github.event.release.prerelease"
        id: deploy
        uses: 10up/action-wordpress-plugin-deploy@stable
        env:
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
